# Generated by Django 4.0.2 on 2022-02-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='short_url',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
